### PR TITLE
Merge pages' code into one + many bug fixes

### LINKED ISSUE #96: Merge article page code with plyta tygodnia page code
Merge the code for plyta tygodnia page with article page into one widget, because they share a lot of code

### PR DESCRIPTION
**Pull request by julianuziemblo**
- merge code from `ArticlePage`, `PlytaTygodniaPage`, and `AboutUsPage` into `HtmlContentWithTitleAndImagePage`
- (hopefully) fix disposed controller used error
- fix article_selection_page to properly load and display all articles
- fix about_us_page to display the RA logo
- add l10n to repository for easier code synchronization and building after changes

Closes #96

### CODE REVIEW

File: mobile/lib/components/newest_article/newest_article_widget.dart [hunk 1]
```diff
@@ -42,16 +42,11 @@ class NewestArticleWidget extends HookWidget {
 
     return SwipeableCard(
       items: articles.value.mapIndexed(
```
Comment (Kszesiek) [inline mobile/lib/components/newest_article/newest_article_widget.dart:44]: I know it's not really targeting your changes, but we might as well address this now. Seems like mapIndexed is not necessary here, a simple map would be sufficient - unless we're planning to use index value for something in the near future. This of course requires removing index parameter in the next line.
```suggestion
      items: articles.value.map(
```

Comment (julianuziemblo) [reply mobile/lib/components/newest_article/newest_article_widget.dart]: yup, I think I overlooked it when refactoring

**Review by Kszesiek — APPROVED** [review]
Najs!

File: mobile/lib/components/utility/lazy_loaded_grid_view.dart [hunk 2]
```diff
@@ -157,7 +157,8 @@ _LazyLoadingController<T> _useLazyLoadingController<T>(
           fetchItems();
         }
       });
-      return scrollController.dispose;
+      return;
+      // return scrollController.dispose;
```
[the remark this answers is not in the document]
Comment (julianuziemblo) [reply mobile/lib/components/utility/lazy_loaded_grid_view.dart:161]: I think so! scrollController is a hook object and should be disposed by itself
